# excel import

## Materials

In [2]:
import pandas as pd

In [128]:
Aplus_export = pd.read_excel("Materials PyroTires.xlsx", skiprows=3, sheet_name=None)
# List of required sheets
def get_sheet_data(sheets, sheet_name):
    if sheet_name in sheets:
        return sheets[sheet_name].iloc[:, 2:]
    else:
        print(f'{sheet_name} sheet is missing!')
        return pd.DataFrame()

# Extract material and heat data
material_df = get_sheet_data(Aplus_export, 'Material')

# Create new DataFrames based on 'From' and 'To' conditions if material_df is not empty
if not material_df.empty:
    output_df = material_df.loc[:, material_df.iloc[1].notna()].iloc[[30,36]]
    input_df = material_df.loc[:, material_df.iloc[2].notna()].iloc[[30,36]]
    unit_df = material_df.iloc[[30,36],[0,1]]
else:
    output_df = pd.DataFrame()
    input_df = pd.DataFrame()

     Stream Name  Units
15    Mass Flows  kg/hr
117  Volume Flow  l/min

In [50]:
material_df.loc[:, material_df.iloc[1].notna()]

,Stream Name,ASHPROD,BCARBON,FUELOIL,GASCOMB,GASOUT1,GASOUT2,GASOUT3,GASOUT4,GASPROD,...,POSTRXN,PREDECOM,PREHEAT,PRERXN,SOLIDS,WATOUT1,WATOUT2,WATOUT3,WATOUT4,WATXHAUS
0,Description,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,From,CARBOSEP,CARBOSEP,OILMIX,FURNACE,HX1,HX2,HX3,HX4,SOLSEP,...,PYRROL,SHREDDER,PREHX,DECOMP,SOLSEP,HX1,HX2,HX3,HX4,HX-RECOV
2,To,NaN,NaN,NaN,HEATREC2,HX2,HX3,HX4,FURNACE,HX1,...,SOLSEP,PREHX,DECOMP,PYRROL,CARBOSEP,HX-RECOV,HX1,HX2,HX3,NaN
3,Stream Class,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,...,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD,MIXNCPSD
4,Maximum Relative Error,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,0 - 0.164 ft,0.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.9,0.9,0.9,0.9,0.9,NaN,NaN,NaN,NaN,NaN
1003,- 0.3281 ft,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.1,0.1,0.1,0.1,0.1,NaN,NaN,NaN,NaN,NaN
1004,- 0.8202 ft,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
1005,- 1.64 ft,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
1006,- 3.281 ft,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN

In [56]:
material_df.iloc[[1,2]]

,Stream Name,Units,AIR,ASHPROD,BCARBON,FTIRE,FUELOIL,GASCOMB,GASOUT1,GASOUT2,...,PREDECOM,PREHEAT,PRERXN,SOLIDS,WATIN4,WATOUT1,WATOUT2,WATOUT3,WATOUT4,WATXHAUS
1,From,NaN,NaN,CARBOSEP,CARBOSEP,NaN,OILMIX,FURNACE,HX1,HX2,...,SHREDDER,PREHX,DECOMP,SOLSEP,NaN,HX1,HX2,HX3,HX4,HX-RECOV
2,To,NaN,FURNACE,NaN,NaN,SHREDDER,NaN,HEATREC2,HX2,HX3,...,PREHX,DECOMP,PYRROL,CARBOSEP,HX4,HX-RECOV,HX1,HX2,HX3,NaN

In [129]:
material_df_t = material_df.set_index('Stream Name').T

# Filter the columns based on the conditions
outputs = (material_df_t['From'].notna()) & (material_df_t['To'].isna())
output_df_t = material_df_t.loc[outputs,:]

# Transpose back to the original format
output_tot_df = output_df_t.T.reset_index()
output_df=pd.concat([output_tot_df.loc[(output_tot_df['Stream Name']=='Mass Flows')].iloc[[0]], output_tot_df.loc[(output_tot_df['Stream Name']=='Volume Flow')].iloc[[0]]]).reset_index(drop=True)
output_df

   Stream Name   ASHPROD    BCARBON    FUELOIL    GASXHAUS WATXHAUS
0   Mass Flows     20.55   32.94964  85.154031   23.346329    49.75
1  Volume Flow  0.098225  61.027022   1.818231  445.246888  0.83059

In [68]:
pd.concat([filtered_df.iloc[[1,2]],filtered_df.loc[(filtered_df['Stream Name']=='Mass Flows')].iloc[[0]], filtered_df.loc[(filtered_df['Stream Name']=='Volume Flow')].iloc[[0]]])

     Stream Name   ASHPROD    BCARBON    FUELOIL    GASXHAUS  WATXHAUS
1           From  CARBOSEP   CARBOSEP     OILMIX    HEATREC2  HX-RECOV
2             To       NaN        NaN        NaN         NaN       NaN
15    Mass Flows     20.55   32.94964  85.154031   23.346329     49.75
117  Volume Flow  0.098225  61.027022   1.818231  445.246888   0.83059

In [60]:
material_filtered_df = pd.concat([material_df.iloc[[1,2]],material_df.loc[(material_df['Stream Name']=='Mass Flows')].iloc[[0]], material_df.loc[(material_df['Stream Name']=='Volume Flow')].iloc[[0]]])
material_filtered_df

,Stream Name,Units,AIR,ASHPROD,BCARBON,FTIRE,FUELOIL,GASCOMB,GASOUT1,GASOUT2,...,PREDECOM,PREHEAT,PRERXN,SOLIDS,WATIN4,WATOUT1,WATOUT2,WATOUT3,WATOUT4,WATXHAUS
1,From,NaN,NaN,CARBOSEP,CARBOSEP,NaN,OILMIX,FURNACE,HX1,HX2,...,SHREDDER,PREHX,DECOMP,SOLSEP,NaN,HX1,HX2,HX3,HX4,HX-RECOV
2,To,NaN,FURNACE,NaN,NaN,SHREDDER,NaN,HEATREC2,HX2,HX3,...,PREHX,DECOMP,PYRROL,CARBOSEP,HX4,HX-RECOV,HX1,HX2,HX3,NaN
15,Mass Flows,kg/hr,12.0,20.55,32.94964,150,85.154031,23.346329,96.50036,94.956382,...,150,150,150,53.49964,49.75,49.75,49.75,49.75,49.75,49.75
117,Volume Flow,l/min,156.887531,0.098225,61.027022,1.994553,1.818231,1200.840826,923.232003,635.58746,...,1.994553,1.994553,5957.077866,61.125247,0.830553,1382.224378,965.585161,412.071842,0.833401,0.83059

In [ ]:
pd.merge(material_df.iloc[[30,36],[0,1]], material_df.loc[:, material_df.iloc[2].notna()].iloc[[30,36]], on='Stream Name')

In [18]:
material_df.iloc[[30, 36], [0, 1]]

    Stream Name  Units
30   Mass Flows  kg/hr
36  Volume Flow  l/min

In [72]:
unit_df = material_df.iloc[[30,36],[0,1]]

In [9]:
df = pd.merge(unit_df,input_df, on='Stream Name').set_index('Stream Name').T
df['Type'] = 'Input'
dff = output_df.set_index('Stream Name').T
pd.concat([df, dff])

Stream Name Mass Flows  Volume Flow   Type
Units            kg/hr        l/min  Input
FEED          120000.0  2379.991137  Input
FEED 2        120000.0  2379.991137  Input
FEED 3        120000.0  2379.991137  Input
BTMS           73380.0  1334.811905    NaN
DIST           46620.0  1025.877458    NaN

In [112]:
input_df = pd.merge(material_df.iloc[[30,36],[0,1]], material_df.loc[:, material_df.iloc[1].notna()].iloc[[30,36]], on='Stream Name')

In [11]:
df = input_df.set_index('Stream Name').T
df['Type'] = 'Input'
dff = output_df.set_index('Stream Name').T
# df = pd.concat([df, dff])

In [76]:
unit_df[unit_df['Stream Name'] == 'Mass Flows']['Units'].values[0]

'kg/hr'

In [75]:
conversion_factors = {
    'kg/hr': 1,  # Assuming kg/hr stays as kg/hr, no conversion needed
    'l/min': 0.001 * 60  # Convert l/min to cubic meters per hour (m³/hr)
}

# Apply conversions
mass_unit = unit_df[unit_df['Stream Name'] == 'Mass Flows']['Units'].values[0]
volume_unit = unit_df[unit_df['Stream Name'] == 'Volume Flow']['Units'].values[0]

df['Mass Flows'] = df['Mass Flows'] * conversion_factors[mass_unit]
df['Volume Flow'] = df['Volume Flow'] * conversion_factors[volume_unit]

df

Stream Name Mass Flows Volume Flow   Type
FEED          120000.0  142.799468  Input
FEED 2        120000.0  142.799468  Input
FEED 3        120000.0  142.799468  Input
BTMS           73380.0   80.088714    NaN
DIST           46620.0   61.552647    NaN

In [44]:
[input for input in output_df.columns[1:]]

['BTMS', 'DIST']

In [8]:
material_df.loc[:, material_df.iloc[1].notna()].iloc[[30,36]].set_index('Stream Name').T

Stream Name Mass Flows  Volume Flow
BTMS           73380.0  1334.811905
DIST           46620.0  1025.877458

In [59]:
output_df

    Stream Name         BTMS         DIST
30   Mass Flows      73380.0      46620.0
36  Volume Flow  1334.811905  1025.877458

In [61]:
dff = output_df.set_index('Stream Name').T
dff

Stream Name Mass Flows  Volume Flow
BTMS           73380.0  1334.811905
DIST           46620.0  1025.877458

In [36]:
df = input_df.set_index('Stream Name').T
df['Type'] = 'Input'
dff = output_df.set_index('Stream Name').T
materials_data = pd.concat([df, dff])
materials_data

Stream Name Mass Flows  Volume Flow   Type
FEED          120000.0  2379.991137  Input
FEED 2        120000.0  2379.991137  Input
FEED 3        120000.0  2379.991137  Input
BTMS           73380.0  1334.811905    NaN
DIST           46620.0  1025.877458    NaN

In [72]:
input_df.iloc[[30,36]]

    Stream Name         FEED       FEED 2       FEED 3
30   Mass Flows     120000.0     120000.0     120000.0
36  Volume Flow  2379.991137  2379.991137  2379.991137

In [49]:
range(1, len(input_df.columns))

range(1, 2)

In [47]:
output_df.columns[2]

'DIST'

In [50]:
input_df.columns

Index(['Stream Name', 'FEED'], dtype='object')

In [39]:
output_df.columns[1:]

Index(['BTMS', 'DIST'], dtype='object')

In [123]:
input_df = pd.merge(material_df.iloc[[30,36],[0,1]], material_df.loc[:, material_df.iloc[2].notna()].iloc[[30,36]], on='Stream Name')

In [124]:
input_df

   Stream Name  Units         FEED       FEED 2       FEED 3
0   Mass Flows  kg/hr     120000.0     120000.0     120000.0
1  Volume Flow  l/min  2379.991137  2379.991137  2379.991137

## Utility

In [207]:
utility_df = pd.read_excel("Utilities PyroTires.xlsx").iloc[[0,2,3]].rename(columns={'Utility ID':'Stream Name', 'Unnamed: 1':'Units'})
util_unit_df=utility_df.iloc[1:, :2]
util_df = utility_df.iloc[1:, :].drop(columns=['Units']).set_index('Stream Name').T

In [86]:
utility_df = pd.read_excel("Utilities PyroTires.xlsx").rename(columns={'Utility ID':'Stream Name', 'Unnamed: 1':'Units'})

In [88]:
utility_df

,Stream Name,Units,ELECTRIC,U-1
0,Utility type,NaN,ELECTRICITY,GENERAL
1,Costing rate,$/hr,0.062605,0.8336
2,Mass flow,kg/hr,NaN,326.901903
3,Duty,MJ/hr,2.908111,196.141141
4,Heating/Cooling value,MJ/kg,NaN,0.6
5,CO2 emission factor data source,NaN,US-EPA-RULE-E9-5711,US-EPA-RULE-E9-5711
6,Ultimate fuel source,NaN,NATURAL_GAS,NATURAL_GAS
7,CO2 emission factor,kg/cal,0.0,0.0
8,CO2 energy source efficiency factor,NaN,0.58,0.85
9,CO2 emission rate,kg/hr,0.280231,12.896843
10,Purchase price,NaN,NaN,NaN
11,Electricity price,$/kWhr,0.0775,NaN
12,Energy price,$/cal,NaN,0.0
13,Inlet temperature,C,NaN,1000
14,Outlet temperature,C,NaN,400
15,Inlet pressure,NaN,NaN,NaN
16,Outlet pressure,NaN,NaN,NaN
17,Inlet vapor fraction,NaN,NaN,NaN
18,Outlet vapor fraction,NaN,NaN,NaN
19,Inlet enthalpy,NaN,NaN,NaN
20,Outlet enthalpy,NaN,NaN,NaN

In [90]:
uti = utility_df.loc[(utility_df['Stream Name']=='Utility type')|(utility_df['Stream Name']=='Ultimate fuel source')|(utility_df['Stream Name']=='Mass flow')|(utility_df['Stream Name']=='Duty')].reset_index(drop=True)

In [95]:
uti

            Stream Name  Units     ELECTRIC          U-1
0          Utility type    NaN  ELECTRICITY      GENERAL
1             Mass flow  kg/hr          NaN   326.901903
2                  Duty  MJ/hr     2.908111   196.141141
3  Ultimate fuel source    NaN  NATURAL_GAS  NATURAL_GAS

In [101]:
uti.loc??

Type:        property
String form: <property object at 0x0000023D5289CAE0>
Source:
# uti.loc.fget
@property
def loc(self) -> _LocIndexer:
    """
    Access a group of rows and columns by label(s) or a boolean array.

    ``.loc[]`` is primarily label based, but may also be used with a
    boolean array.

    Allowed inputs are:

    - A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
      interpreted as a *label* of the index, and **never** as an
      integer position along the index).
    - A list or array of labels, e.g. ``['a', 'b', 'c']``.
    - A slice object with labels, e.g. ``'a':'f'``.

      .. warning:: Note that contrary to usual python slices, **both** the
          start and the stop are included

    - A boolean array of the same length as the axis being sliced,
      e.g. ``[True, False, True]``.
    - An alignable boolean Series. The index of the key will be aligned before
      masking.
    - An alignable Index. The Index of the returned selection will be the input.
    - A ``callable`` function with one argument (the calling Series or
      DataFrame) and that returns valid output for indexing (one of the above)

    See more at :ref:`Selection by Label <indexing.label>`.

    Raises
    ------
    KeyError
        If any items are not found.
    IndexingError
        If an indexed key is passed and its index is unalignable to the frame index.

    See Also
    --------
    DataFrame.at : Access a single value for a row/column label pair.
    DataFrame.iloc : Access group of rows and columns by integer position(s).
    DataFrame.xs : Returns a cross-section (row(s) or column(s)) from the
                   Series/DataFrame.
    Series.loc : Access group of values using labels.

    Examples
    --------
    **Getting values**

    >>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
    ...                   index=['cobra', 'viper', 'sidewinder'],
    ...                   columns=['max_speed', 'shield'])
    >>> df
                max_speed  shield
    cobra               1       2
    viper               4       5
    sidewinder          7       8

    Single label. Note this returns the row as a Series.

    >>> df.loc['viper']
    max_speed    4
    shield       5
    Name: viper, dtype: int64

    List of labels. Note using ``[[]]`` returns a DataFrame.

    >>> df.loc[['viper', 'sidewinder']]
                max_speed  shield
    viper               4       5
    sidewinder          7       8

    Single label for row and column

    >>> df.loc['cobra', 'shield']
    2

    Slice with labels for row and single label for column. As mentioned
    above, note that both the start and stop of the slice are included.

    >>> df.loc['cobra':'viper', 'max_speed']
    cobra    1
    viper    4
    Name: max_speed, dtype: int64

    Boolean list with the same length as the row axis

    >>> df.loc[[False, False, True]]
                max_speed  shield
    sidewinder          7       8

    Alignable boolean Series:

    >>> df.loc[pd.Series([False, True, False],
    ...                  index=['viper', 'sidewinder', 'cobra'])]
                         max_speed  shield
    sidewinder          7       8

    Index (same behavior as ``df.reindex``)

    >>> df.loc[pd.Index(["cobra", "viper"], name="foo")]
           max_speed  shield
    foo
    cobra          1       2
    viper          4       5

    Conditional that returns a boolean Series

    >>> df.loc[df['shield'] > 6]
                max_speed  shield
    sidewinder          7       8

    Conditional that returns a boolean Series with column labels specified

    >>> df.loc[df['shield'] > 6, ['max_speed']]
                max_speed
    sidewinder          7

    Multiple conditional using ``&`` that returns a boolean Series

    >>> df.loc[(df['max_speed'] > 1) & (df['shield'] < 8)]
                max_speed  shield
    viper          4       5

    Multiple conditional using ``|`` that returns a boolean Series

    >>> df.loc[(df['max_speed'] > 4) | (df['shield'] < 5)]
                max_speed  shield
    cobra               1       2
    sidewinder          7       8

    Please ensure that each condition is wrapped in parentheses ``()``.
    See the :ref:`user guide<indexing.boolean>`
    for more details and explanations of Boolean indexing.

    .. note::
        If you find yourself using 3 or more conditionals in ``.loc[]``,
        consider using :ref:`advanced indexing<advanced.advanced_hierarchical>`.

        See below for using ``.loc[]`` on MultiIndex DataFrames.

    Callable that returns a boolean Series

    >>> df.loc[lambda df: df['shield'] == 8]
                max_speed  shield
    sidewinder          7       8

    **Setting values**

    Set value for all items matching the list of labels

    >>> df.loc[['viper', 'sidewinder'], ['shield']] = 50
    >>> df
                max_speed  shield
    cobra               1       2
    viper               4      50
    sidewinder          7      50

    Set value for an entire row

    >>> df.loc['cobra'] = 10
    >>> df
                max_speed  shield
    cobra              10      10
    viper               4      50
    sidewinder          7      50

    Set value for an entire column

    >>> df.loc[:, 'max_speed'] = 30
    >>> df
                max_speed  shield
    cobra              30      10
    viper              30      50
    sidewinder         30      50

    Set value for rows matching callable condition

    >>> df.loc[df['shield'] > 35] = 0
    >>> df
                max_speed  shield
    cobra              30      10
    viper               0       0
    sidewinder          0       0

    Add value matching location

    >>> df.loc["viper", "shield"] += 5
    >>> df
                max_speed  shield
    cobra              30      10
    viper               0       5
    sidewinder          0       0

    Setting using a ``Series`` or a ``DataFrame`` sets the values matching the
    index labels, not the index positions.

    >>> shuffled_df = df.loc[["viper", "cobra", "sidewinder"]]
    >>> df.loc[:] += shuffled_df
    >>> df
                max_speed  shield
    cobra              60      20
    viper               0      10
    sidewinder          0       0

    **Getting values on a DataFrame with an index that has integer labels**

    Another example using integers for the index

    >>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
    ...                   index=[7, 8, 9], columns=['max_speed', 'shield'])
    >>> df
       max_speed  shield
    7          1       2
    8          4       5
    9          7       8

    Slice with integer labels for rows. As mentioned above, note that both
    the start and stop of the slice are included.

    >>> df.loc[7:9]
       max_speed  shield
    7          1       2
    8          4       5
    9          7       8

    **Getting values with a MultiIndex**

    A number of examples using a DataFrame with a MultiIndex

    >>> tuples = [
    ...     ('cobra', 'mark i'), ('cobra', 'mark ii'),
    ...     ('sidewinder', 'mark i'), ('sidewinder', 'mark ii'),
    ...     ('viper', 'mark ii'), ('viper', 'mark iii')
    ... ]
    >>> index = pd.MultiIndex.from_tuples(tuples)
    >>> values = [[12, 2], [0, 4], [10, 20],
    ...           [1, 4], [7, 1], [16, 36]]
    >>> df = pd.DataFrame(values, columns=['max_speed', 'shield'], index=index)
    >>> df
                         max_speed  shield
    cobra      mark i           12       2
               mark ii           0       4
    sidewinder mark i           10      20
               mark ii           1       4
    viper      mark ii           7       1
               mark iii         16      36

    Single label. Note this returns a DataFrame with a single index.

    >>> df.loc['cobra']
             max_speed  shield
    mark i          12       2
    mark ii          0       4

    Single index tuple. Note this returns a Series.

    >>> df.loc[('cobra', 'mark ii')]
    max_speed    0
    shield       4
    Name: (cobra, mark ii), dtype: int64

    Single label for row and column. Similar to passing in a tuple, this
    returns a Series.

    >>> df.loc['cobra', 'mark i']
    max_speed    12
    shield        2
    Name: (cobra, mark i), dtype: int64

    Single tuple. Note using ``[[]]`` returns a DataFrame.

    >>> df.loc[[('cobra', 'mark ii')]]
                   max_speed  shield
    cobra mark ii          0       4

    Single tuple for the index with a single label for the column

    >>> df.loc[('cobra', 'mark i'), 'shield']
    2

    Slice from index tuple to single label

    >>> df.loc[('cobra', 'mark i'):'viper']
                         max_speed  shield
    cobra      mark i           12       2
               mark ii           0       4
    sidewinder mark i           10      20
               mark ii           1       4
    viper      mark ii           7       1
               mark iii         16      36

    Slice from index tuple to index tuple

    >>> df.loc[('cobra', 'mark i'):('viper', 'mark ii')]
                        max_speed  shield
    cobra      mark i          12       2
               mark ii          0       4
    sidewinder mark i          10      20
               mark ii          1       4
    viper      mark ii          7       1

    Please see the :ref:`user guide<advanced.advanced_hierarchical>`
    for more details and explanations of advanced indexing.
    """
    return _LocIndexer("loc", self)

In [118]:
uti[uti['Stream Name'] == 'Ultimate fuel source'].iloc[0,2]

'NATURAL_GAS'

In [115]:
print(uti.loc[uti['Stream Name']=='Utility type', uti.columns[2]])

0    ELECTRICITY
Name: ELECTRIC, dtype: object

In [212]:
conversion_factors = {
    'kg/hr': 1,  # Assuming kg/hr stays as kg/hr, no conversion needed
    'l/min': 0.001 * 60 , # Convert l/min to cubic meters per hour (m³/hr)
    'tonne/year': 1000/(365*24),
    'MJ/hr' : 1
}

In [215]:
util_df = utility_df.iloc[1:, :].drop(columns=['Units']).set_index('Stream Name').T
util_df.rename(columns={'Mass flow':'Mass Flows'}, inplace=True)
util_df

Stream Name       Mass Flows         Duty
CW              43003.473971   102.410478
HPSTEAMG           503.54983    98.763993
LPSTEAM           319.003001    79.764541
LPSTEAMG         1449.678367   362.482265
VHT          10760582.107892  1227.536172

In [213]:
util_unit_df=utility_df.iloc[1:, :2]
util_df = utility_df.iloc[1:, :].drop(columns=['Units']).set_index('Stream Name').T
util_df.rename(columns={'Mass flow':'Mass Flows'}, inplace=True)
mass_unit = util_unit_df[util_unit_df['Stream Name'] == 'Mass flow']['Units'].values[0]
energy_unit = util_unit_df[util_unit_df['Stream Name'] == 'Duty']['Units'].values[0]
util_df['Type'] = 'Utility'
util_df_reset = util_df.reset_index()
util_df_reset['Mass flow'] = util_df_reset['Mass Flows'] * conversion_factors[mass_unit]
util_df_reset['Duty'] = util_df_reset['Duty'] * conversion_factors[energy_unit]

In [208]:
util_unit_df

  Stream Name       Units
2   Mass flow  tonne/year
3        Duty       MJ/hr

In [187]:
utility_df

,Stream Name,Units,CW,HPSTEAMG,LPSTEAM,LPSTEAMG,VHT
0,Utility type,NaN,WATER,STEAM,STEAM,STEAM,GENERAL
2,Mass flow,tonne/year,43003.473971,503.54983,319.003001,1449.678367,10760582.107892
3,Duty,MJ/hr,102.410478,98.763993,79.764541,362.482265,1227.536172

In [210]:
util_df.rename(columns={'Mass flow':'Mass Flows'}, inplace=True)

In [211]:
util_df

Stream Name       Mass Flows         Duty
CW              43003.473971   102.410478
HPSTEAMG           503.54983    98.763993
LPSTEAM           319.003001    79.764541
LPSTEAMG         1449.678367   362.482265
VHT          10760582.107892  1227.536172

In [173]:
util_unit_df

  Stream Name       Units
2   Mass flow  tonne/year
3        Duty       MJ/hr

In [48]:
i = 2
utilities_df.iloc[0, i]

'WATER'

In [3]:
utilities_df.columns[2:]

Index(['CW', 'HPSTEAMG', 'LPSTEAM', 'LPSTEAMG', 'VHT'], dtype='object')

In [10]:
utilities_df.iloc[0,2:]

CW            WATER
HPSTEAMG      STEAM
LPSTEAM       STEAM
LPSTEAMG      STEAM
VHT         GENERAL
Name: 0, dtype: object

In [41]:
utilities_df

,Utility ID,Unnamed: 1,CW,HPSTEAMG,LPSTEAM,LPSTEAMG,VHT
0,Utility type,NaN,WATER,STEAM,STEAM,STEAM,GENERAL
1,Costing rate,$/hr,0.021711,-0.245922,0.151553,-0.685091,10.925075
2,Mass flow,tonne/year,43003.473971,503.54983,319.003001,1449.678367,10760582.107892
3,Duty,MJ/hr,102.410478,98.763993,79.764541,362.482265,1227.536172
4,Heating/Cooling value,Btu/lb,-8.974962,-739.176143,942.338338,-942.338338,0.429923
5,CO2 emission factor data source,NaN,NaN,US-EPA-RULE-E9-5711,US-EPA-RULE-E9-5711,US-EPA-RULE-E9-5711,US-EPA-RULE-E9-5711
6,Ultimate fuel source,NaN,NaN,NATURAL_GAS,NATURAL_GAS,NATURAL_GAS,NATURAL_GAS
7,CO2 emission factor,lb/Btu,NaN,0.00013,0.00013,0.00013,0.00013
8,CO2 energy source efficiency factor,NaN,1,-0.85,0.85,-0.85,0.85
9,CO2 emission rate,lb/hr,NaN,-14.316855,11.562689,-52.545525,177.94397
10,Purchase price,NaN,NaN,NaN,NaN,NaN,NaN
11,Electricity price,NaN,NaN,NaN,NaN,NaN,NaN
12,Energy price,$/Btu,0.0,-0.000003,0.000002,-0.000002,0.000009
13,Inlet temperature,F,68,480.2,257,255.2,5432
14,Outlet temperature,F,77,482,255.2,257,5430.2
15,Inlet pressure,psia,14.695949,566.904206,33.674685,32.650971,NaN
16,Outlet pressure,psia,14.695949,576.578902,32.650971,33.674685,NaN
17,Inlet vapor fraction,NaN,0,0,1,0,NaN
18,Outlet vapor fraction,NaN,0,1,0,1,NaN
19,Inlet enthalpy,Btu/lb,-6830.03907,-6401.87119,-5700.21317,-6642.55151,NaN
20,Outlet enthalpy,Btu/lb,-6821.0641,-5662.69505,-6642.55151,-5700.21317,NaN

In [40]:
types = ['Reference flow', 'Waste', 'Waste', None]
None not in types

False

In [39]:
any(types)

True

# ecoinvent search

In [1]:
import bw2analyzer as ba
import bw2data as bd
import bw2calc as bc
import bw2io as bi
import matrix_utils as mu
import bw_processing as bp

In [208]:
[proj for proj in list(bd.projects)]

[Project: default,
 Project: ESHOE,
 Project: BIOED,
 Project: PASTA,
 Project: water impact,
 Project: OWC,
 Project: Agritechnica,
 Project: Temporalis example project,
 Project: Ecoinvent 3.9.1 cut-off,
 Project: PLAYGROUND,
 Project: LEGNO2,
 Project: LIG,
 Project: Green_waste,
 Project: Ecoinvent-3.10-cut-off,
 Project: Ecoinvent-3.10-consequential,
 Project: Chapter24,
 Project: PLAYGROUND_FINALE,
 Project: advlca23,
 Project: advlca20_heat_exercise,
 Project: advlca23_Aalborg]

In [209]:
bd.projects

Brightway2 projects manager with 20 objects:
	Agritechnica
	BIOED
	Chapter24
	ESHOE
	Ecoinvent 3.9.1 cut-off
	Ecoinvent-3.10-consequential
	Ecoinvent-3.10-cut-off
	Green_waste
	LEGNO2
	LIG
	OWC
	PASTA
	PLAYGROUND
	PLAYGROUND_FINALE
	Temporalis example project
	advlca20_heat_exercise
	advlca23
	advlca23_Aalborg
	default
	water impact
Use `projects.report()` to get a report on all projects.

In [3]:
bd.projects.set_current("Ecoinvent-3.10-cut-off")

In [36]:
dbase = [db for db in bd.databases if 'asp_b_db' in db ]
del bd.databases[dbase]

IndexError: list index out of range

In [5]:
ei_db = bd.Database("ecoinvent-3.10-cutoff")
bio_db = bd.Database("ecoinvent-3.10-biosphere")

In [148]:
bio_db.search('carbon dioxide')

['Carbon dioxide, fossil' (kilogram, None, ('air', 'lower stratosphere + upper troposphere')),
 'Carbon dioxide, fossil' (kilogram, None, ('air',)),
 'Carbon dioxide, fossil' (kilogram, None, ('air', 'urban air close to ground')),
 'Carbon dioxide, fossil' (kilogram, None, ('air', 'low population density, long-term')),
 'Carbon dioxide, fossil' (kilogram, None, ('air', 'non-urban air or from high stacks')),
 'Carbon dioxide, non-fossil' (kilogram, None, ('air', 'non-urban air or from high stacks')),
 'Carbon dioxide, non-fossil' (kilogram, None, ('air', 'low population density, long-term')),
 'Carbon dioxide, in air' (kilogram, None, ('natural resource', 'in air')),
 'Carbon dioxide, non-fossil' (kilogram, None, ('air', 'urban air close to ground')),
 'Carbon dioxide, non-fossil' (kilogram, None, ('air',)),
 'Carbon dioxide, non-fossil, resource correction' (kilogram, None, ('natural resource', 'in air')),
 'Carbon dioxide, from soil or biomass stock' (kilogram, None, ('air', 'non-urban air or from high stacks')),
 'Carbon dioxide, from soil or biomass stock' (kilogram, None, ('air',)),
 'Carbon dioxide, from soil or biomass stock' (kilogram, None, ('air', 'urban air close to ground')),
 'Carbon dioxide, to soil or biomass stock' (kilogram, None, ('soil',)),
 'Carbon dioxide, to soil or biomass stock' (kilogram, None, ('soil', 'agricultural')),
 'Carbon dioxide, to soil or biomass stock' (kilogram, None, ('soil', 'forestry')),
 'Carbon dioxide, from soil or biomass stock' (kilogram, None, ('air', 'low population density, long-term')),
 'Carbon dioxide, to soil or biomass stock' (kilogram, None, ('soil', 'industrial'))]

In [152]:
flow_list[0].as_dict()

{'categories': ('air', 'lower stratosphere + upper troposphere'),
 'code': '16eeda8a-1ea2-408e-ab37-2648495058dd',
 'CAS number': '000124-38-9',
 'synonyms': ['Carbon dioxide'],
 'name': 'Carbon dioxide, fossil',
 'database': 'ecoinvent-3.10-biosphere',
 'unit': 'kilogram',
 'type': 'emission',
 'id': 1033}

In [154]:
bd.get_node(code='16eeda8a-1ea2-408e-ab37-2648495058dd')

'Carbon dioxide, fossil' (kilogram, None, ('air', 'lower stratosphere + upper troposphere'))

In [157]:
[item for item in flow_list]

[]

In [162]:
[ef for ef in bio_db if 'natural' in str(ef['categories'])]

['Transformation, to lake, artificial' (square meter, None, ('natural resource', 'land')),
 'Transformation, to industrial area' (square meter, None, ('natural resource', 'land')),
 'Occupation, forest, unspecified' (square meter-year, None, ('natural resource', 'land')),
 'Boron' (kilogram, None, ('natural resource', 'in ground')),
 'Actinium' (kilogram, None, ('natural resource', 'in ground')),
 'Gas, mine, off-gas, process, coal mining' (standard cubic meter, None, ('natural resource', 'in ground')),
 'Strontium' (kilogram, None, ('natural resource', 'in ground')),
 'Yttrium' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from permanent crop, irrigated, intensive' (square meter, None, ('natural resource', 'land')),
 'Silver' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, to forest, primary (non-use)' (square meter, None, ('natural resource', 'land')),
 'Wood, hard, standing' (cubic meter, None, ('natural resource', 'biotic')),
 'Tellurium' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, arable, reduced tillage (obsolete)' (square meter, None, ('natural resource', 'land')),
 'Transformation, from forest, primary (non-use)' (square meter, None, ('natural resource', 'land')),
 'Thorium' (kilogram, None, ('natural resource', 'in ground')),
 'Samarium' (kilogram, None, ('natural resource', 'in ground')),
 'Uranium' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from urban, continuously built' (square meter, None, ('natural resource', 'land')),
 'Water, unspecified natural origin' (cubic meter, None, ('natural resource', 'fossil well')),
 'Transformation, to annual crop, non-irrigated' (square meter, None, ('natural resource', 'land')),
 'Silicon' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from dump site, residual material landfill' (square meter, None, ('natural resource', 'land')),
 'Transformation, from annual crop, non-irrigated, intensive' (square meter, None, ('natural resource', 'land')),
 'Occupation, permanent crop, non-irrigated' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to grassland, natural, for livestock grazing' (square meter, None, ('natural resource', 'land')),
 'Transformation, from urban, green area' (square meter, None, ('natural resource', 'land')),
 'Occupation, seabed, infrastructure' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to seabed, drilling and mining' (square meter, None, ('natural resource', 'land')),
 'Transformation, from seabed, drilling and mining' (square meter, None, ('natural resource', 'land')),
 'Selenium' (kilogram, None, ('natural resource', 'in ground')),
 'Sulfur' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from urban/industrial fallow (non-use)' (square meter, None, ('natural resource', 'land')),
 'Gallium' (kilogram, None, ('natural resource', 'in ground')),
 'Volume occupied, underground deposit' (cubic meter, None, ('natural resource', 'in ground')),
 'Occupation, annual crop' (square meter-year, None, ('natural resource', 'land')),
 'Tin' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from permanent crop' (square meter, None, ('natural resource', 'land')),
 'Lutetium' (kilogram, None, ('natural resource', 'in ground')),
 'Indium' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, arable, conventional tillage (obsolete)' (square meter, None, ('natural resource', 'land')),
 'Transformation, from annual crop, flooded crop' (square meter, None, ('natural resource', 'land')),
 'Transformation, from permanent crop, irrigated, extensive' (square meter, None, ('natural resource', 'land')),
 'Transformation, to dump site' (square meter, None, ('natural resource', 'land')),
 'Occupation, urban, discontinuously built' (square meter-year, None, ('natural resource', 'land')),
 'Chromium' (kilogram, None, ('natural resource', 'in ground')),
 'Vanadium' (kilogram, None, ('natural resource', 'in ground')),
 'Chrysotile' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, forest, extensive' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, from pasture, man made, intensive' (square meter, None, ('natural resource', 'land')),
 'Stibnite' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from traffic area, rail/road embankment' (square meter, None, ('natural resource', 'land')),
 'Water, well, in ground' (cubic meter, None, ('natural resource', 'in water')),
 'Phosphorus' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, to inland waterbody, unspecified' (square meter, None, ('natural resource', 'land')),
 'Occupation, urban, continuously built' (square meter-year, None, ('natural resource', 'land')),
 'Occupation, grassland, natural (non-use)' (square meter-year, None, ('natural resource', 'land')),
 'Water, turbine use, unspecified natural origin' (cubic meter, None, ('natural resource', 'in water')),
 'Colemanite' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from urban, discontinuously built' (square meter, None, ('natural resource', 'land')),
 'Carnallite' (kilogram, None, ('natural resource', 'in water')),
 'Spodumene' (kilogram, None, ('natural resource', 'in ground')),
 'Zirconium' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, to cropland fallow (non-use)' (square meter, None, ('natural resource', 'land')),
 'Transformation, from wetland, coastal (non-use)' (square meter, None, ('natural resource', 'land')),
 'Occupation, arable land, unspecified use' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, from field margin/hedgerow' (square meter, None, ('natural resource', 'land')),
 'Gadolinium' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, permanent crop, non-irrigated, intensive' (square meter-year, None, ('natural resource', 'land')),
 'Lanthanum' (kilogram, None, ('natural resource', 'in ground')),
 'Holmium' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, industrial area' (square meter-year, None, ('natural resource', 'land')),
 'Feldspar' (kilogram, None, ('natural resource', 'in ground')),
 'Protactinium' (kilogram, None, ('natural resource', 'in ground')),
 'Basalt' (kilogram, None, ('natural resource', 'in ground')),
 'Granite' (kilogram, None, ('natural resource', 'in ground')),
 'Calcite' (kilogram, None, ('natural resource', 'in ground')),
 'Fluorspar' (kilogram, None, ('natural resource', 'in ground')),
 'Nickel' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from forest, intensive' (square meter, None, ('natural resource', 'land')),
 'Transformation, from river, artificial' (square meter, None, ('natural resource', 'land')),
 'Occupation, forest, secondary (non-use)' (square meter-year, None, ('natural resource', 'land')),
 'Occupation, permanent crop, irrigated, extensive' (square meter-year, None, ('natural resource', 'land')),
 'Occupation, river, artificial' (square meter-year, None, ('natural resource', 'land')),
 'Occupation, permanent crop, irrigated, intensive' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to annual crop, non-irrigated, extensive' (square meter, None, ('natural resource', 'land')),
 'Rhodium' (kilogram, None, ('natural resource', 'in ground')),
 'Sodium' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from forest, extensive' (square meter, None, ('natural resource', 'land')),
 'Occupation, unspecified' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, from annual crop, non-irrigated, extensive' (square meter, None, ('natural resource', 'land')),
 'Terbium' (kilogram, None, ('natural resource', 'in ground')),
 'Dysprosium' (kilogram, None, ('natural resource', 'in ground')),
 'Barium' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from seabed, unspecified' (square meter, None, ('natural resource', 'land')),
 'Kieserite' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from annual crop, irrigated, extensive' (square meter, None, ('natural resource', 'land')),
 'Occupation, field margin/hedgerow' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, from pasture, man made, extensive' (square meter, None, ('natural resource', 'land')),
 'Transformation, to permanent crop, irrigated, extensive' (square meter, None, ('natural resource', 'land')),
 'Occupation, urban/industrial fallow (non-use)' (square meter-year, None, ('natural resource', 'land')),
 'Ytterbium' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, dump site' (square meter-year, None, ('natural resource', 'land')),
 'Gypsum' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, to dump site, inert material landfill' (square meter, None, ('natural resource', 'land')),
 'Occupation, annual crop, flooded crop' (square meter-year, None, ('natural resource', 'land')),
 'Thulium' (kilogram, None, ('natural resource', 'in ground')),
 'Germanium' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, shrub land, sclerophyllous' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, from arable land, unspecified use' (square meter, None, ('natural resource', 'land')),
 'Osmium' (kilogram, None, ('natural resource', 'in ground')),
 'Molybdenum' (kilogram, None, ('natural resource', 'in ground')),
 'Manganese' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from snow and ice (non-use)' (square meter, None, ('natural resource', 'land')),
 'Transformation, from grassland, natural, for livestock grazing' (square meter, None, ('natural resource', 'land')),
 'Transformation, from forest, secondary (non-use)' (square meter, None, ('natural resource', 'land')),
 'Caesium' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, permanent crop, irrigated' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to lake, natural (non-use)' (square meter, None, ('natural resource', 'land')),
 'Transformation, to urban/industrial fallow (non-use)' (square meter, None, ('natural resource', 'land')),
 'Krypton' (kilogram, None, ('natural resource', 'in air')),
 'Transformation, from unspecified' (square meter, None, ('natural resource', 'land')),
 'Gangue' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, urban, green area' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, from annual crop, non-irrigated' (square meter, None, ('natural resource', 'land')),
 'Talc' (kilogram, None, ('natural resource', 'in ground')),
 'Energy, gross calorific value, in biomass, primary forest' (megajoule, None, ('natural resource', 'biotic')),
 'Tungsten' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, seabed, natural (non-use)' (square meter-year, None, ('natural resource', 'land')),
 'Ulexite' (kilogram, None, ('natural resource', 'in ground')),
 'Magnesite' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from unknown' (square meter, None, ('natural resource', 'land')),
 'Occupation, snow and ice (non-use)' (square meter-year, None, ('natural resource', 'land')),
 'Occupation, annual crop, greenhouse' (square meter-year, None, ('natural resource', 'land')),
 'Iron' (kilogram, None, ('natural resource', 'in ground')),
 'Carbon, organic, in soil or biomass stock' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, forest, primary (non-use)' (square meter-year, None, ('natural resource', 'land')),
 'Hafnium' (kilogram, None, ('natural resource', 'in ground')),
 'Astatine' (kilogram, None, ('natural resource', 'in ground')),
 'Laterite' (kilogram, None, ('natural resource', 'in ground')),
 'Palladium' (kilogram, None, ('natural resource', 'in ground')),
 'Cobalt' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, annual crop, non-irrigated, extensive' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to permanent crop, non-irrigated, intensive' (square meter, None, ('natural resource', 'land')),
 'Copper' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, to permanent crop, irrigated, intensive' (square meter, None, ('natural resource', 'land')),
 'Transformation, to permanent crop, irrigated' (square meter, None, ('natural resource', 'land')),
 'Occupation, seabed, unspecified' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to mineral extraction site' (square meter, None, ('natural resource', 'land')),
 'Transformation, from grassland, natural (non-use)' (square meter, None, ('natural resource', 'land')),
 'Sylvite' (kilogram, None, ('natural resource', 'in ground')),
 'Oil, crude' (kilogram, None, ('natural resource', 'in ground')),
 'Nitrogen' (kilogram, None, ('natural resource', 'in air')),
 'Niobium' (kilogram, None, ('natural resource', 'in ground')),
 'Sodium nitrate' (kilogram, None, ('natural resource', 'in ground')),
 'Polonium' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, to wetland, inland (non-use)' (square meter, None, ('natural resource', 'land')),
 'Transformation, from annual crop, irrigated, intensive' (square meter, None, ('natural resource', 'land')),
 'Energy, kinetic (in wind), converted' (megajoule, None, ('natural resource', 'in air')),
 'Occupation, annual crop, irrigated' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to field margin/hedgerow' (square meter, None, ('natural resource', 'land')),
 'Transformation, to permanent crop, non-irrigated' (square meter, None, ('natural resource', 'land')),
 'Fish, pelagic, in ocean' (kilogram, None, ('natural resource', 'biotic')),
 'Fish, demersal, in ocean' (kilogram, None, ('natural resource', 'biotic')),
 'Occupation, heterogeneous, agricultural' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, from unspecified, natural (non-use)' (square meter, None, ('natural resource', 'land')),
 'Transformation, to unknown' (square meter, None, ('natural resource', 'land')),
 'Volume occupied, final repository for radioactive waste' (cubic meter, None, ('natural resource', 'in ground')),
 'Occupation, annual crop, irrigated, intensive' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, from permanent crop, non-irrigated' (square meter, None, ('natural resource', 'land')),
 'Occupation, lake, natural (non-use)' (square meter-year, None, ('natural resource', 'land')),
 'Occupation, pasture, man made' (square meter-year, None, ('natural resource', 'land')),
 'Occupation, annual crop, irrigated, extensive' (square meter-year, None, ('natural resource', 'land')),
 'Occupation, seabed, drilling and mining' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to annual crop' (square meter, None, ('natural resource', 'land')),
 'Occupation, inland waterbody, unspecified' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to seabed, natural (non-use)' (square meter, None, ('natural resource', 'land')),
 'Transformation, to forest, intensive' (square meter, None, ('natural resource', 'land')),
 'Occupation, traffic area, road network' (square meter-year, None, ('natural resource', 'land')),
 'Dolomite' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, to river, artificial' (square meter, None, ('natural resource', 'land')),
 'Fluorine' (kilogram, None, ('natural resource', 'in ground')),
 'Erbium' (kilogram, None, ('natural resource', 'in ground')),
 'Water, unspecified natural origin' (cubic meter, None, ('natural resource', 'in ground')),
 'Occupation, wetland, coastal (non-use)' (square meter-year, None, ('natural resource', 'land')),
 'Neodymium' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, to forest, extensive' (square meter, None, ('natural resource', 'land')),
 'Xenon' (kilogram, None, ('natural resource', 'in air')),
 'Occupation, pasture, man made, extensive' (square meter-year, None, ('natural resource', 'land')),
 'Sodium chloride' (kilogram, None, ('natural resource', 'in ground')),
 'Aluminium' (kilogram, None, ('natural resource', 'in ground')),
 'Rhenium' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from permanent crop, irrigated' (square meter, None, ('natural resource', 'land')),
 'Occupation, mineral extraction site' (square meter-year, None, ('natural resource', 'land')),
 'Vermiculite' (kilogram, None, ('natural resource', 'in ground')),
 'Bismuth' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, grassland, natural, for livestock grazing' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to annual crop, non-irrigated, intensive' (square meter, None, ('natural resource', 'land')),
 'Transformation, from lake, natural (non-use)' (square meter, None, ('natural resource', 'land')),
 'Transformation, to urban, discontinuously built' (square meter, None, ('natural resource', 'land')),
 'Titanium' (kilogram, None, ('natural resource', 'in ground')),
 'Water, lake' (cubic meter, None, ('natural resource', 'in water')),
 'Perlite' (kilogram, None, ('natural resource', 'in ground')),
 'Praseodymium' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, to forest, secondary (non-use)' (square meter, None, ('natural resource', 'land')),
 'Occupation, construction site' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to annual crop, greenhouse' (square meter, None, ('natural resource', 'land')),
 'Occupation, bare area (non-use)' (square meter-year, None, ('natural resource', 'land')),
 'Magnesium' (kilogram, None, ('natural resource', 'in water')),
 'Transformation, from industrial area' (square meter, None, ('natural resource', 'land')),
 'Volume occupied, final repository for low-active radioactive waste' (cubic meter, None, ('natural resource', 'in ground')),
 'Occupation, forest, intensive' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, to forest, unspecified' (square meter, None, ('natural resource', 'land')),
 'Transformation, to dump site, slag compartment' (square meter, None, ('natural resource', 'land')),
 'Occupation, arable, conservation tillage (obsolete)' (square meter, None, ('natural resource', 'land')),
 'Occupation, annual crop, non-irrigated, intensive' (square meter-year, None, ('natural resource', 'land')),
 'Energy, solar, converted' (megajoule, None, ('natural resource', 'in air')),
 'Steatite' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from inland waterbody, unspecified' (square meter, None, ('natural resource', 'land')),
 'Transformation, to arable land, unspecified use' (square meter, None, ('natural resource', 'land')),
 'Transformation, from mineral extraction site' (square meter, None, ('natural resource', 'land')),
 'Kaolinite' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, cropland fallow (non-use)' (square meter-year, None, ('natural resource', 'land')),
 'Rubidium' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, traffic area, rail network' (square meter-year, None, ('natural resource', 'land')),
 'Lithium' (kilogram, None, ('natural resource', 'in ground')),
 'Transformation, from dump site, inert material landfill' (square meter, None, ('natural resource', 'land')),
 'Pyrite' (kilogram, None, ('natural resource', 'in ground')),
 'Occupation, unspecified, natural (non-use)' (square meter-year, None, ('natural resource', 'land')),
 'Transformation, from seabed, infrastructure' (square meter, None, ('natural resource', 'land')),
 'Transformation, to annual crop, irrigated, intensive' (square meter, None, ('natural resource', 'land')),

In [167]:
bio='carbon'

In [168]:
flow_list = bio_db.search(f'natural {bio}', limit=50)
# [{'label': f"{item['name']}, {item['category']}", 'value': item[1]} for item in flow_list]

In [169]:
flow_list

['Carbon dioxide, in air' (kilogram, None, ('natural resource', 'in air')),
 'Carbon dioxide, non-fossil, resource correction' (kilogram, None, ('natural resource', 'in air')),
 'Carbon, organic, in soil or biomass stock' (kilogram, None, ('natural resource', 'in ground'))]

In [ ]:
ei_db.search(Any, )

In [38]:
[act['name'] for act in ei_db if act['production amount']<0]

['market for residues, MSWI, spent anion exchange resin from potable water production',
 'market for electric arc furnace dust',
 'market for residues, MSWI, municipal solid waste',
 'clinker production',
 'market for residues, MSWI[F], waste paperboard',
 'market for spent catalyst base from ethyleneoxide production',
 'clinker production',
 'treatment of used triple glazing, U<0.5W/m2K, collection for final disposal',
 'treatment of municipal solid waste, open dump, very wet infiltration class (1000mm)',
 'market for conditioned spent nuclear fuel',
 'treatment of residue from mechanical treatment, desktop computer, municipal incineration FAE',
 'market for used room-connecting overflow element steel, approx. 40 m3/h',
 'treatment of bottom ash, MSWI, waste polyvinylfluoride, slag compartment',
 'market for waste polyurethane',
 'market for used blower and heat exchange unit decentralized, 180-250 m3/h',
 'market for limestone residue',
 'market for waste graphical paper',
 'market for residues, MSWI-WWT, WW from maize starch production',
 'market for waste paperboard',
 'treatment of waste cement in concrete and mortar, collection for final disposal',
 'treatment of residues, MSWI, municipal solid waste, residual material landfill',
 'market for wastewater from cathode ray tube production',
 'market for used blower and heat exchange unit KWL 250',
 'clinker production',
 'market for wastewater from PV cell production',
 'treatment of used blower and heat exchange unit, Avent E 97',
 'clinker production',
 'market for waste polyurethane',
 'market for hard coal ash',
 'treatment of sewage sludge, 70% water, WWT, WW from maize starch production, municipal incineration',
 'market for waste glass',
 'market for used air filter in exhaust air valve',
 'market for bottom ash, MSWI, waste emulsion paint',
 'market for residues, MSWI-WWT-SLF, waste aluminium',
 'treatment of waste polyethylene, unsanitary landfill, dry infiltration class (100mm)',
 'market for bottom ash, MSWI[F]-WWT-SLF, waste graphical paper',
 'market for waste plastic, mixture',
 'market for residue from shredder fraction from manual dismantling',
 'treatment, sludge from pulp and paper production, landfarming',
 'treatment of used refrigeration machine, carbon dioxide, liquid as refrigerant',
 'market for bottom ash, MSWI-WWT, WW, average',
 'treatment of residues, MSWI-WWT-SLF, waste plastic, mixture, residual material landfill',
 'treatment of sewage sludge, 70% water, WWT-SLF, sludge from pulp and paper production, municipal incineration',
 'market for waste glass pane in burnable frame',
 'treatment of sewage sludge, 97% water, WWT-SLF, waste polypropylene, landfarming',
 'market for waste glass',
 'treatment of sewage sludge, 97% water, WWT, WW, average, landfarming',
 'market for residues, MSWI-WWT, WW from CRT production',
 'market for waste polyvinylchloride',
 'concrete production, 25MPa, for building construction, for interior use, with cement ZN/D, with 50% RC-C aggregates',
 'treatment of residues, MSWI-WWT-SLF, scrap tin sheet, residual material landfill',
 'treatment of bilge oil, hazardous waste incineration, with energy recovery',
 'market for waste emulsion paint, on wood',
 'market for waste electric wiring',
 'treatment of bottom ash, MSWI, waste polyethylene terephthalate, slag compartment',
 'treatment of spent pot liner from Al electrolysis, carbon fraction, residual material landfill',
 'market for residues, MSWI, steel in car shredder residue',
 'market for residues, MSWI[F]-WWT, condensate from light oil boiler',
 'market for waste wood, untreated',
 'treatment of municipal solid waste, sanitary landfill',
 'treatment of wastewater from liquid crystal display production, wastewater treatment',
 'treatment of waste polystyrene isolation, flame-retardant, collection for final disposal',
 'treatment of residues, MSWI, LDPE in waste fresh milk carton (chilled), post-industrial, residual material landfill',
 'treatment of sewage sludge, 75% water, WWT, WW from glass production, sanitary landfill',
 'treatment of bottom ash, MSWI[F], waste wire plastic, slag compartment',
 'treatment of sulfidic tailings, from zinc-lead mine operation, tailings impoundment',
 'treatment of residues, MSWI-WWT, condensate from light oil boiler, residual material landfill',
 'market for leachate, SLF, residue from cooling tower',
 'market for bottom ash, MSWI[F]-WWT, WW from LCD backlight production',
 'market for waste glass',
 'treatment of sewage sludge, 97% water, WWT, WW from PV cell production, landfarming',
 'treatment of sewage sludge, 70% water, WWT-SLF, waste asphalt, municipal incineration FAE',
 'concrete production, 50MPa, with cement, Portland',
 'market for waste polyethylene',
 'market for sewage sludge, 97% water, WWT, WW from liquid crystal production',
 'market for waste polyurethane',
 'market for dross from Al electrolysis',
 'treatment of used tram',
 'market for wastewater from ceramic production',
 'treatment of waste emulsion paint, on wood, collection for final disposal',
 'market for waste graphical paper',
 'market for bottom ash, MSWI[F], used LCD module',
 'cement production, CP II-Z',
 'treatment of used ventilation control and wiring, central unit',
 'treatment of sewage sludge, 97% water, WWT-SLF, waste paint, landfarming',
 'market for waste glass',
 'treatment of waste yarn and waste textile, unsanitary landfill',
 'market for municipal solid waste',
 'treatment of waste paint, hazardous waste incineration, with energy recovery',
 'treatment of bottom ash, MSWI-WWT, WW from liquid crystal production, slag compartment',
 'treatment of wastewater from liquid crystal production, wastewater treatment',
 'market for waste frit from cathode ray tube production',
 'market for leachate, SLF, scrap tin sheet',
 'market for sewage sludge, 97% water, WWT, WW from concrete production',
 'market for wastewater from maize starch production',
 'market for wastewater from black chrome coating',
 'treatment of residues, MSWI, waste paint, residual material landfill',
 'market for waste glass',
 'market for green liquor dregs',
 'market for bottom ash, MSWI, waste polyvinylchloride',
 'treatment of biowaste, open dump',
 'treatment of used cathode ray tube display, manual dismantling',
 'basic oxygen furnace sludge to market for basic oxygen furnace sludge, for recovery',
 'treatment of scrap steel, inert material landfill',
 'market for bottom ash, MSWI[F]-WWT-SLF, waste polypropylene',
 'market for waste electric and electronic equipment',
 'treatment of used electric bicycle',
 'treatment of waste polystyrene, open dump, wet infiltration class (500mm)',
 'market for residues, MSWI-WWT-SLF, waste polyurethane',
 'market for bottom ash, MSWI[F], waste sealing sheet, polyethylene',
 'treatment of waste polyvinylchloride product, collection for final disposal',
 'market for bottom ash, MSWI-WWT-SLF, waste polyethylene terephthalate',
 'market for residues, MSWI[F], waste cement-fibre slab, dismantled',
 'treatment of sludge, NaCl electrolysis, residual material landfill',
 'treatment of waste paperboard, inert material landfill',
 'treatment of sewage sludge, 97% water, WWT, WW from wafer fabrication, landfarming',
 'treatment of bottom ash, MSWI-WWT-SLF, waste plastic plaster, slag compartment',
 'market for sewage sludge, 70% water, WWT-SLF, waste polypropylene',
 'market for wastewater from liquid crystal display backlight production',
 'market for waste polyvinylchloride',
 'market for leachate, SLF, waste packaging paper',
 'treatment of sulfidic tailings, from zinc-lead mine operation, tailings impoundment',
 'treatment of sewage sludge, 97% water, WWT, WW from ceramic production, landfarming',
 'treatment of spent pot liner from Al electrolysis, carbon fraction, residual material landfill',
 'market for residues, MSWI-WWT-SLF, sludge from pulp and paper production',
 'treatment of waste reinforcement steel, recycling',
 'market for used refrigeration machine, R134a as refrigerant',
 'treatment of residue from mechanical treatment, desktop computer, municipal incineration',
 'market for bottom ash, MSWI, LDPE/Alu in waste UHT milk carton (ambient), post-industrial',
 'market for waste glass',
 'market for waste polyethylene terephthalate',
 'market for zinc in car shredder residue',
 'treatment of leachate, SLF, waste plastic plaster, wastewater treatment',
 'treatment of sewage sludge, 75% water, WWT, rainwater mineral oil storage, sanitary landfill',
 'market for waste concrete',
 'treatment of residues, MSWI-WWT, WW from ammonium paratungstate production, residual material landfill',
 'market for municipal solid waste',
 'market for bottom ash, MSWI-WWT, WW, average',
 'market for hard coal ash',
 'market for waste plastic, mixture',
 'market for residues, MSWI[F]-WWT-SLF, waste newspaper',
 'market for waste polystyrene',
 'market for residue from Na-dichromate production',
 'market for bottom ash, MSWI[F]-WWT, WW from ceramic production',
 'treatment of sewage sludge, 70% water, WWT-SLF, waste polypropylene, municipal incineration',
 'market for bottom ash, MSWI, lignite ash',
 'treatment of sewage sludge, 97% water, WWT-SLF, waste aluminium, landfarming',
 'treatment of used liquid crystal display, manual dismantling',
 'market for waste polyethylene',
 'clinker production',
 'treatment of tyre wear emissions, lorry',
 'market for leachate, SLF, hard coal ash',
 'market for waste paperboard',
 'treatment of sewage sludge, 97% water, WWT-SLF, waste polyethylene terephthalate, landfarming',
 'treatment of municipal solid waste, municipal incineration',
 'treatment of waste natural gas, sweet, burned in production flare',
 'market for waste gypsum',
 'market for used door, outer, wood-aluminium',
 'treatment of bottom ash, MSWI[F], steel in car shredder residue, slag compartment',
 'market for waste mineral oil',
 'treatment of sewage sludge, 75% water, WWT, WW from vegetable oil refinery, sanitary landfill',
 'cement production, CEM IV/A',
 'treatment of used double glazing, U<1.1W/m2K, collection for final disposal',
 'treatment of bottom ash, MSWI[F]-WWT-SLF, waste plastic plaster, slag compartment',
 'treatment of sewage sludge, 97% water, WWT, WW from potato starch production, landfarming',
 'treatment of bottom ash, MSWI, waste emulsion paint, slag compartment',
 'treatment of waste polyethylene, open dump, dry infiltration class (100mm)',
 'market for sewage sludge, 70% water, WWT, WW from LCD production',
 'market for sewage sludge, 70% water, WWT-SLF, waste bitumen',
 'treatment of waste polyethylene/polypropylene product, collection for final disposal',
 'treatment of low level radioactive waste, in interim storage',
 'market for sewage sludge, 97% water, WWT-SLF, waste polystyrene',
 'market for waste x-ray film',
 'market for decommissioned chemical production facilities',
 'market for waste polyethylene',
 'market for bottom ash, MSWI[F], biowaste',
 'clinker production',
 'market for waste polyvinylchloride',
 'clinker production',
 'treatment of waste polyvinylchloride, unsanitary landfill, moist infiltration class (300mm)',
 'market for waste wood, untreated',
 'market for waste polyethylene terephthalate',
 'treatment of hard coal ash, residual material landfill',
 'treatment of sewage sludge, 97% water, WWT, WW from medium density board production, landfarming',
 'market for dross from Al electrolysis',
 'market for bilge oil',
 'market for redmud from bauxite digestion',
 'treatment of bottom ash, MSWI-WWT, WW from ammonium paratungstate production, slag compartment',
 'treatment of spoil from lignite mining, in surface landfill',
 'market for bottom ash, MSWI, aluminium in car shredder residue',
 'market for waste polypropylene',
 'treatment of non-Fe-Co-metals, from used Li-ion battery, pyrometallurgical processing',
 'clinker production',
 'treatment of used refrigerant R134a, reclamation',
 'market for residues, MSWI, waste plastic, mixture',
 'market for used cathode ray tube display',
 'treatment of lignite ash, opencast refill',
 'clinker production',
 'treatment of leachate, SLF, wood ash mixture, pure, wastewater treatment',
 'treatment of copper in car shredder residue, municipal incineration FAE',
 'clinker production',
 'concrete production, 25MPa, for building construction, for interior use, with cement, Portland',
 'treatment of waste mineral plaster, collection for final disposal',
 'market for residues, MSWI[F], copper in car shredder residue',
 'heat production, untreated waste wood, at furnace 1000-5000 kW, state-of-the-art 2014',
 'market for bottom ash, MSWI[F], lignite ash',
 'market for wastewater, unpolluted',
 'market for waste paperboard',
 'market for refinery sludge',
 'market for residues, MSWI-WWT, WW from vegetable oil refinery',
 'market for waste foundry sand',
 'market for waste polypropylene',
 'market for residues, MSWI, waste expanded polystyrene',
 'treatment of sulfidic tailings, from copper mine operation, tailings impoundment',
 'market for bottom ash, MSWI, municipal solid waste',
 'treatment of bottom ash, MSWI-WWT-SLF, waste polystyrene, slag compartment',
 'market for residues, MSWI[F], spent cation exchange resin from potable water production',
 'treatment of residues, MSWI-WWT, WW from soft fibreboard production, residual material landfill',
 'market for municipal solid waste',
 'treatment of waste bitumen, sanitary landfill',
 'treatment of waste glass, municipal incineration FAE',
 'treatment of leachate, SLF, sludge from pulp and paper production, wastewater treatment',
 'market for fly ash and scrubber sludge',
 'treatment of waste, electrical and electronic cables, open burning',
 'market for waste polyurethane',
 'treatment of used printer, laser, manual dismantling',
 'market for used blower and heat exchange unit central, 600-1200 m3/h',
 'market for spent nuclear fuel',
 'heat production, untreated waste wood, at furnace 1000-5000 kW, state-of-the-art 2014',
 'treatment of waste expanded polystyrene, municipal incineration',
 'market for bottom ash, MSWI-WWT-SLF, waste aluminium',
 'market for bottom ash, MSWI-WWT, WW from hard fibreboard production',
 'market for residues, MSWI[F]-WWT, WW from wafer fabrication',
 'treatment of waste polyethylene/polypropylene product, collection for final disposal',
 'treatment of bottom ash, MSWI-WWT-SLF, sludge from pulp and paper production, slag compartment',
 'market for residues, MSWI-WWT, WW from PV cell production',
 'treatment of water discharge from petroleum extraction, offshore',
 'treatment of used refrigerant R600a, venting',
 'treatment of bottom ash, MSWI[F], residue from mechanical treatment, CRT display, slag compartment',
 'treatment of municipal solid waste, municipal incineration',
 'market for sewage sludge, 70% water, WWT-SLF, waste plastic plaster',
 'market for residues, MSWI, scrap tin sheet',
 'market for bottom ash, MSWI[F]-WWT, WW from liquid crystal production',
 'market for sewage sludge, 97% water, WWT, rainwater mineral oil storage',
 'market for residues, MSWI, residue from mechanical treatment, laptop computer',
 'market for raw sewage sludge',
 'treatment of waste polyethylene, open burning',
 'market for bottom ash, MSWI-WWT-SLF, waste polyurethane',
 'market for waste wood, untreated',
 'treatment of sewage sludge, 75% water, WWT, WW from pig iron production, sanitary landfill',
 'clinker production',
 'market for sewage sludge, 97% water, WWT, WW from concrete production',
 'treatment of residues, MSWI[F], steel in car shredder residue, residual material landfill',
 'market for residues, MSWI-WWT, WW from GGBFS production',
 'market for waste polystyrene',
 'market for sewage sludge, 70% water, WWT-SLF, waste polyvinylchloride',
 'treatment of waste wood, untreated, unsanitary landfill, dry infiltration class (100mm)',
 'market for bottom ash, MSWI[F]-WWT, WW from CRT production',
 'market for waste polyvinylchloride product',
 'market for waste glass',
 'clinker production',
 'treatment of leachate, SLF, waste polyvinylchloride, wastewater treatment',
 'treatment of residues, MSWI-WWT, WW from LCD production, residual material landfill',
 'market for residues, MSWI-WWT, WW, average',
 'market for sewage sludge, 97% water, WWT-SLF, waste polyvinylchloride',
 'market for residues, MSWI-WWT-SLF, inert waste',
 'treatment of used door, outer, wood-aluminium, collection for final disposal',
 'treatment of waste polyethylene terephthalate, sanitary landfill',
 'treatment of waste polyethylene, unsanitary landfill, very wet infiltration class (1000mm)',
 'treatment of residues, MSWI, municipal solid waste, residual material landfill',
 'market for leachate, SLF, lignite ash',
 'treatment of waste cement-fibre slab, recycling',
 'treatment of municipal solid waste, unsanitary landfill, wet infiltration class (500mm)',
 'treatment of sewage sludge, 70% water, WWT, WW from GGBFS production, municipal incineration',
 'treatment of residues, MSWI[F], waste polypropylene, residual material landfill',
 'market for sewage sludge, 97% water, WWT, WW from particle board production',
 'treatment of used blower and heat exchange unit, central, 600-1200 m3/h',
 'treatment of Sn-based antifouling paint emissions',
 'treatment of redmud from bauxite digestion, residual material landfill',
 'treatment of used bicycle',
 'treatment of waste paint on metal, sorting plant',
 'market for waste polystyrene',
 'treatment of residues, MSWI, municipal solid waste, residual material landfill',
 'treatment of lignite ash, opencast refill',
 'treatment of wastewater from plywood production, wastewater treatment',
 'treatment of residues, MSWI-WWT-SLF, waste graphical paper, residual material landfill',
 'treatment of waste polyurethane, open dump, hyperarid infiltration class (-250mm)',
 'treatment of sewage sludge, 75% water, WWT, WW from particle board production, sanitary landfill',
 'treatment of waste reinforcement steel, sorting plant',
 'market for waste emulsion paint',
 'treatment of residues, MSWI, lead in car shredder residue, residual material landfill',
 'market for bottom ash, MSWI[F], waste plastic, industrial electronics',
 'market for waste paperboard',
 'treatment of waste plastic, mixture, municipal incineration',
 'market for bottom ash, MSWI-WWT-SLF, waste packaging paper',
 'treatment of basic oxygen furnace secondary metallurgy slag, residual material landfill',
 'treatment of sludge from FeCl3 production, underground deposit',
 'clinker production',
 'heat production, untreated waste wood, at furnace 1000-5000 kW',
 'market for used exhaust air roof hood steel, DN 400',
 'market for waste polyethylene terephthalate',
 'treatment of residues, MSWI, waste plastic, mixture, residual material landfill',
 'market for bottom ash, MSWI[F]-WWT[U], WW from lorry production',
 'market for waste polystyrene',
 'market for wastewater, average',
 'treatment of bottom ash, MSWI, municipal solid waste, slag compartment',
 'market for sulfidic tailings, from gold mine operation',
 'market for leachate, SLF, scrap tin sheet',
 'market for used perfluoropentane',
 'market group for waste polyethylene',
 'market for tailing, from uranium milling',
 'market for waste polyethylene terephthalate',
 'treatment of bottom ash, MSWI[F]-WWT-SLF, waste paint, slag compartment',
 'treatment of used window frame, plastic, collection for final disposal',
 'treatment of residues, MSWI, municipal solid waste, residual material landfill',
 'market for sewage sludge, 97% water, WWT, WW from black chrome coating',
 'treatment of leachate, SLF, hard coal ash, wastewater treatment',
 'treatment of refinery sludge, hazardous waste incineration',
 'treatment of residues, MSWI[F]-WWT-SLF, waste gypsum, residual material landfill',
 'market for used Li-ion battery',
 'clinker production',
 'treatment of municipal solid waste, municipal incineration',
 'clinker production',

In [40]:
data = {
    'Stream Name': ['AIR', 'FTIRE', 'WATIN4', 'ASHPROD', 'BCARBON', 'FUELOIL', 'GASXHAUS', 'WATXHAUS'],
    'Type': ['Technosphere', 'No impact', 'Biosphere', 'Waste flow', 'Biosphere flow', 'Reference flow', None, None],
    'Activity': ['d6df845e50b67e6905979a8ed391b9fc', None, '478e8437-1c21-4032-8438-872a6b5ddcdf', 'd53d6ba8c615bf13c5722c6df5ea5533', '349b29d1-3e58-4c66-98b9-9d1a076efd2e', None, None, None],
    'Act unit': ['cubic meter', None, 'cubic meter', 'kilogram', 'kilogram', 'kilogram', 'kilogram', 'kilogram'],
    'Amount': [0.110544, 0.000000, 0.000585, -0.241327, 0.386942, 1.000000, 0.274166, 0.584235]
}
in_df = pd.DataFrame(data)
act_df = pd.concat([in_df[in_df['Type'].str.contains('Reference', na=False)], in_df[in_df['Type'].str.contains('Biosphere', na=False)]]).reset_index(drop=True)
act_df

,Stream Name,Type,Activity,Act unit,Amount
0,FUELOIL,Reference flow,None,kilogram,1.000000
1,WATIN4,Biosphere,478e8437-1c21-4032-8438-872a6b5ddcdf,cubic meter,0.000585
2,BCARBON,Biosphere flow,349b29d1-3e58-4c66-98b9-9d1a076efd2e,kilogram,0.386942

In [53]:
amount_exc[0]

'cubic meter'

In [76]:
act_df.loc[act_df['Type']=='Reference flow', 'Activity']=act_df.loc[act_df['Type']=='Reference flow', 'Stream Name']

In [77]:
act_df

,Stream Name,Type,Activity,Act unit,Amount
0,FUELOIL,Reference flow,FUELOIL,kilogram,1.000000
1,WATIN4,Biosphere,478e8437-1c21-4032-8438-872a6b5ddcdf,cubic meter,0.000585
2,BCARBON,Biosphere flow,349b29d1-3e58-4c66-98b9-9d1a076efd2e,kilogram,0.386942

In [73]:
def create_ref_act(df):
    ref = df.loc[df['Type']=='Reference flow', 'Stream Name'].iloc[0]
    try:
        ref_act = ei_db.new_node(code=ref,name=ref, location="Aspen_bw", type='process', unit="kilogram")
    except:
        ref_act = bd.get_node(code = ref)
        ref_act.delete()
        ref_act = ei_db.new_node(code=ref,name=ref, location="Aspen_bw", type='process', unit="kilogram")
    for i in range(len(df[df['Type'].str.contains('Biosphere', na=False)]['Activity'])):
        code_exc = df[df['Type'].str.contains('Biosphere', na=False)]['Activity'].iloc[i]
        unit_exc = df[df['Type'].str.contains('Biosphere', na=False)]['Act unit'].iloc[i]
        amount_exc = df[df['Type'].str.contains('Biosphere', na=False)]['Amount'].iloc[i]

        act = bd.get_node(code= code_exc)
        ref_act.new_edge(input=act.key, 
                            amount=amount_exc,
                            unit=unit_exc, 
                            type='biosphere').save()
        ref_act.save()
    
    return ref_act

In [57]:
in_df[in_df['Type'].str.contains('Biosphere', na=False)]['Activity'].iloc[0]

'478e8437-1c21-4032-8438-872a6b5ddcdf'

In [78]:
act_df[~act_df['Type'].str.contains('Biosphere', na=False)]

  Stream Name            Type Activity  Act unit  Amount
0     FUELOIL  Reference flow  FUELOIL  kilogram     1.0

In [72]:
ref = act_df.loc[act_df['Type']=='Reference flow', 'Stream Name'].iloc[0]
bd.get_node(code=ref)

'FUELOIL' (kilogram, Aspen_bw, None)

In [66]:
code_exc

['478e8437-1c21-4032-8438-872a6b5ddcdf',
 '349b29d1-3e58-4c66-98b9-9d1a076efd2e']

In [75]:
ref_act = create_ref_act(act_df)

In [69]:
ref_act

'FUELOIL' (kilogram, Aspen_bw, None)

In [55]:
list(ref_act.exchanges())

[Exchange: 0.000585 cubic meter 'Water, unspecified natural origin' (cubic meter, None, ('natural resource', 'in ground')) to 'FUELOIL' (kilogram, Aspen_bw, None)>]

In [38]:
bd.get_node(code = '478e8437-1c21-4032-8438-872a6b5ddcdf')['unit']

'cubic meter'

In [37]:
in_df[~in_df['Type'].str.contains('Biosphere', na=False)]

,Stream Name,Type,Activity,Act unit,Amount
0,AIR,Technosphere,d6df845e50b67e6905979a8ed391b9fc,cubic meter,0.110544
1,FTIRE,No impact,None,None,0.000000
3,ASHPROD,Waste flow,d53d6ba8c615bf13c5722c6df5ea5533,kilogram,-0.241327
5,FUELOIL,Reference flow,None,kilogram,1.000000
6,GASXHAUS,None,None,kilogram,0.274166
7,WATXHAUS,None,None,kilogram,0.584235

In [11]:

output_dict = {
    ('asp_bw_db', act_df.loc[act_df['Type']=='Reference flow', 'Stream Name'].iloc[0]): {
        'name': act_df.loc[act_df['Type']=='Reference flow', 'Stream Name'].iloc[0],
        'unit': act_df.loc[act_df['Type']=='Reference flow', 'Act unit'].iloc[0],
        'type': 'process',
        'exchanges': []
    }
}

# Fill the 'exchanges' list in the dictionary
for index, row in act_df.iterrows():
    if row['Type'] == 'Reference flow':
        exchange = {
            'input': ('asp_bw_db', row['Stream Name']),
            'amount': row['Amount'],
            'unit': row['Act unit'],
            'type': 'production'
        }
    else:
        exchange = {
            'input': ('ecoinvent-3.10-biosphere', row['Activity']),
            'amount': row['Amount'],
            'unit': row['Act unit'],
            'type': 'biosphere'
        }
    
    output_dict[('asp_bw_db', act_df.loc[act_df['Type']=='Reference flow', 'Stream Name'].iloc[0])]['exchanges'].append(exchange)

In [28]:
act_df.loc[act_df['Type']=='Reference flow', 'Activity'] = act_df.loc[act_df['Type']=='Reference flow', 'Stream Name']
act_df

,Stream Name,Type,Activity,Act unit,Amount
0,FUELOIL,Reference flow,FUELOIL,kilogram,1.000000
1,WATIN4,Biosphere,478e8437-1c21-4032-8438-872a6b5ddcdf,cubic meter,0.000585
2,BCARBON,Biosphere flow,349b29d1-3e58-4c66-98b9-9d1a076efd2e,kilogram,0.386942

In [39]:
ref = act_df.loc[act_df['Type']=='Reference flow', 'Stream Name'].iloc[0]
ref_act = ei_db.new_node(code=ref,name=ref, location="Aspen_bw", type='process', unit="kilogram")
ref_act

'FUELOIL' (kilogram, Aspen_bw, None)

In [6]:
del bd.databases['asp_bw_db']

In [12]:
t_db = bd.Database('asp_bw_db') # it works because the database name in the excel file is the same
# shut down all other notebooks using the same project
t_db.write(output_dict)

Not able to determine geocollections for all datasets. This database is not ready for regionalization.

100%|██████████| 1/1 [00:00<00:00, 999.12it/s]

Vacuuming database

In [29]:
try:
    bd.get_node(code='FUELOIL')
except:
    print('activity not present')

activity not present

In [26]:
output_dict = create_node(act_df,bio_db.name)

In [27]:
output_dict

{('asp_bw_db', 'FUELOIL'): {'name': 'FUELOIL',
  'unit': 'kilogram',
  'type': 'process',
  'exchanges': [{'input': ('asp_bw_db', 'FUELOIL'),
    'amount': 1.0,
    'unit': 'kilogram',
    'type': 'production'},
   {'input': ('ecoinvent-3.10-biosphere',
     '478e8437-1c21-4032-8438-872a6b5ddcdf'),
    'amount': 0.000585,
    'unit': 'cubic meter',
    'type': 'biosphere'},
   {'input': ('ecoinvent-3.10-biosphere',
     '349b29d1-3e58-4c66-98b9-9d1a076efd2e'),
    'amount': 0.386942,
    'unit': 'kilogram',
    'type': 'biosphere'}]}}

In [25]:
def create_node(df, bio_db_name):
    node_dict = {
        ('asp_bw_db', df.loc[df['Type']=='Reference flow', 'Stream Name'].iloc[0]): {
            'name': df.loc[df['Type']=='Reference flow', 'Stream Name'].iloc[0],
            'unit': df.loc[df['Type']=='Reference flow', 'Act unit'].iloc[0],
            'type': 'process',
            'exchanges': []
        }
    }

    # Fill the 'exchanges' list in the dictionary
    for index, row in df.iterrows():
        if row['Type'] == 'Reference flow':
            exchange = {
                'input': ('asp_bw_db', row['Stream Name']),
                'amount': row['Amount'],
                'unit': row['Act unit'],
                'type': 'production'
            }
        else:
            exchange = {
                'input': (bio_db_name, row['Activity']),
                'amount': row['Amount'],
                'unit': row['Act unit'],
                'type': 'biosphere'
            }
        
        node_dict[('asp_bw_db', df.loc[df['Type']=='Reference flow', 'Stream Name'].iloc[0])]['exchanges'].append(exchange)

    return node_dict

In [199]:
output_dict

{('asp_bw_db', 'FUELOIL'): {'name': 'FUELOIL',
  'unit': 'kilogram',
  'type': 'process',
  'exchanges': [{'input': ('asp_bw_db', 'FUELOIL'),
    'amount': 1.0,
    'unit': 'kilogram',
    'type': 'production'},
   {'input': ('biosphere3', '478e8437-1c21-4032-8438-872a6b5ddcdf'),
    'amount': 0.000585,
    'unit': 'cubic meter',
    'type': 'biosphere'},
   {'input': ('biosphere3', '349b29d1-3e58-4c66-98b9-9d1a076efd2e'),
    'amount': 0.386942,
    'unit': 'kilogram',
    'type': 'biosphere'}]}}

In [ ]:
act_df.loc[act_df['Type']=='Reference flow', 'Stream Name'].iloc[0]

'FUELOIL'

In [ ]:
{('asp_bw_db', 'Direct impact FUELOIL production'): {'name': 'FUELOIL',
  'unit': 'kilogram',
  'type': 'process',
  'exchanges': [{'input': ('asp_bw_db', 'FUELOIL'),
    'amount': 1,
    'unit': 'kilogram',
    'type': 'production'},
   {'input': ('biosphere3', '478e8437-1c21-4032-8438-872a6b5ddcdf'),
    'amount': 0.000585,
    'unit': 'cubic meter',
    'type': 'biosphere',},
   {'input': ('biosphere3', '349b29d1-3e58-4c66-98b9-9d1a076efd2e'),
    'amount': 0.386942,
    'unit': 'kilogram',
    'type': 'biosphere'}]}
}

In [37]:
bd.get_node(id=21000).as_dict()

{'comment': "Geography:  This activity delivers the product of ''inorganic nitrogen fertiliser, as N'' within the geography of Costa Rica.",
 'classifications': [('ISIC rev.4 ecoinvent',
   '0161:Support activities for crop production'),
  ('CPC', '34619: Other nitrogenous fertilizers and mixtures, n.e.c.')],
 'activity type': 'market activity',
 'activity': 'b4d63a44-3b26-5338-a542-bfceb962ac2d',
 'database': 'ecoinvent-3.10-cutoff',
 'filename': 'b4d63a44-3b26-5338-a542-bfceb962ac2d_f5707bdf-f7e2-479b-b3ea-99c04de8a927.spold',
 'location': 'CR',
 'name': 'market for inorganic nitrogen fertiliser, as N',
 'synonyms': [],
 'parameters': [],
 'authors': {'data entry': {'name': 'Avraam Symeonidis',
   'email': 'Symeonidis@ecoinvent.org'},
  'data generator': {'name': 'Avraam Symeonidis',
   'email': 'Symeonidis@ecoinvent.org'}},
 'type': 'process',
 'reference product': 'inorganic nitrogen fertiliser, as N',
 'flow': 'f5707bdf-f7e2-479b-b3ea-99c04de8a927',
 'unit': 'kilogram',
 'production amount': 1.0,
 'code': '7c1aa706f6ebbdc5fff36ef6509640b6',
 'id': 21000}

In [119]:
ei_act_name = input(f"ecoinvent activity to search")

In [121]:
ei_db.search(ei_act_name, limit = 50)

['electricity production, natural gas, aluminium industry' (kilowatt hour, IAI Area, South America, None),
 'electricity production, natural gas, aluminium industry' (kilowatt hour, IAI Area, Gulf Cooperation Council, None),
 'electricity production, natural gas, aluminium industry' (kilowatt hour, IAI Area, EU27 & EFTA, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, CO, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, CN-GX, None),
 'natural gas, burned in micro gas turbine, 100kWe' (megajoule, CH, None),
 'natural gas, burned in micro gas turbine, 100kWe' (megajoule, RoW, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, US-WECC, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, SA, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, CA-ON, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, TZ, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, RoW, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, CA-MB, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, US-TRE, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IR, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, MY, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, TR, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, UA, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, TH, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, CA-PE, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, KR, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, CL, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, US-ASCC, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, US-RFC, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, ID, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, US-NPCC, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, TW, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, AU, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, CA-SK, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, US-SERC, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, CA-AB, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, RU, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, MX, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, US-MRO, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-HR, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-DL, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-MH, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-TN, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-KA, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-UP, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-KL, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-DN, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-MP, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-AS, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-TR, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-AP, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-GA, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-RJ, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-GJ, None),
 'electricity production, natural gas, conventional power plant' (kilowatt hour, IN-PY, None)]

In [26]:
type(ei_list)

list

In [33]:
dropdown_list = [f"{item['name']}, {item['location']}" for item in ei_list]
dropdown_list

['wood pellet production, RoW',
 'wood pellet production, RER',
 'wood pellet factory production, RER',
 'wood pellet factory production, RoW',
 'wood wool production, RER',
 'wood wool production, RoW',
 'market for wood wool, RoW',
 'market for wood wool, RER',
 'wood wool production, CA-QC',
 'wood chipping, industrial residual wood, stationary electric chipper, RER',
 'wood wool production, RER',
 'wood wool production, RoW',
 'heat production, untreated waste wood, at furnace 1000-5000 kW, CH',
 'heat production, untreated waste wood, at furnace 1000-5000 kW, RoW',
 'furnace production, wood chips, with silo, 50kW, RoW',
 'wood wool production, CA-QC',
 'furnace production, wood chips, with silo, 50kW, CH',
 'furnace production, wood chips, with silo, 300kW, RoW',
 'furnace production, wood chips, with silo, 300kW, CH',
 'market for wood chipping, industrial residual wood, stationary electric chipper, GLO',
 'wood cladding production, softwood, CA-QC',
 'wood cladding production, softwood, CA-QC',
 'wood cladding production, softwood, RoW',
 'wood cladding production, softwood, RoW',
 'furnace production, wood chips, with silo, 5000kW, RoW',
 'furnace production, wood chips, with silo, 1000kW, RoW',
 'furnace production, wood chips, with silo, 5000kW, CH',
 'furnace production, wood chips, with silo, 1000kW, CH',
 'market for residual wood, dry, RoW',
 'market for residual wood, dry, RER',
 'market for wood chips, from post-consumer wood, measured as dry mass, RoW',
 'market for wood chips, from post-consumer wood, measured as dry mass, RER',
 'door production, inner, wood, RER',
 'door production, inner, wood, RoW',
 'market for wood cladding, softwood, GLO',
 'market for energy wood harvester, GLO',
 'market for joist, engineered wood, GLO',
 'market for wood pellet factory, GLO',
 'engineered wood joist production, CA-QC',
 'engineered wood joist production, RoW',
 'market for waste wood, untreated, CH',
 'market for waste wood, untreated, RoW',
 'market for door, inner, wood, GLO',
 'market for waste wood, untreated, BR',
 'wood preservative production, creosote, RER',
 'wood preservative production, creosote, RoW',
 'market for waste wood, untreated, ZA',
 'market for waste wood, untreated, CO',
 'market for waste wood, untreated, PE',
 'market for waste wood, untreated, IN']

# Impact categories

In [34]:
material = 'x'
utility = 'y'
'x' in [material, utility]

True

In [7]:
EF_select = [met for met in bd.methods if met[0] == 'EF v3.1']

In [107]:
[EF_select[i][1] for i in range(len(EF_select))]

['acidification',
 'climate change',
 'climate change: biogenic',
 'climate change: fossil',
 'climate change: land use and land use change',
 'ecotoxicity: freshwater',
 'ecotoxicity: freshwater, inorganics',
 'ecotoxicity: freshwater, organics',
 'energy resources: non-renewable',
 'eutrophication: freshwater',
 'eutrophication: marine',
 'eutrophication: terrestrial',
 'human toxicity: carcinogenic',
 'human toxicity: carcinogenic, inorganics',
 'human toxicity: carcinogenic, organics',
 'human toxicity: non-carcinogenic',
 'human toxicity: non-carcinogenic, inorganics',
 'human toxicity: non-carcinogenic, organics',
 'ionising radiation: human health',
 'land use',
 'material resources: metals/minerals',
 'ozone depletion',
 'particulate matter formation',
 'photochemical oxidant formation: human health',
 'water use']

In [122]:
df = input_df.set_index('Stream Name').T
df['Type'] = 'Input'
# df.reset_index()
df_reset = df.reset_index()
dff_reset =dff.reset_index()
# Step 2: Convert DataFrame to dictionary
data = df_reset.to_dict("records")
data_out=dff_reset.to_dict("records")

In [170]:
bio_db.search('carbon dioxide')

['Carbon dioxide, fossil' (kilogram, None, ('air', 'lower stratosphere + upper troposphere')),
 'Carbon dioxide, fossil' (kilogram, None, ('air',)),
 'Carbon dioxide, fossil' (kilogram, None, ('air', 'urban air close to ground')),
 'Carbon dioxide, fossil' (kilogram, None, ('air', 'low population density, long-term')),
 'Carbon dioxide, fossil' (kilogram, None, ('air', 'non-urban air or from high stacks')),
 'Carbon dioxide, non-fossil' (kilogram, None, ('air', 'non-urban air or from high stacks')),
 'Carbon dioxide, non-fossil' (kilogram, None, ('air', 'low population density, long-term')),
 'Carbon dioxide, in air' (kilogram, None, ('natural resource', 'in air')),
 'Carbon dioxide, non-fossil' (kilogram, None, ('air', 'urban air close to ground')),
 'Carbon dioxide, non-fossil' (kilogram, None, ('air',)),
 'Carbon dioxide, non-fossil, resource correction' (kilogram, None, ('natural resource', 'in air')),
 'Carbon dioxide, from soil or biomass stock' (kilogram, None, ('air', 'non-urban air or from high stacks')),
 'Carbon dioxide, from soil or biomass stock' (kilogram, None, ('air',)),
 'Carbon dioxide, from soil or biomass stock' (kilogram, None, ('air', 'urban air close to ground')),
 'Carbon dioxide, to soil or biomass stock' (kilogram, None, ('soil',)),
 'Carbon dioxide, to soil or biomass stock' (kilogram, None, ('soil', 'agricultural')),
 'Carbon dioxide, to soil or biomass stock' (kilogram, None, ('soil', 'forestry')),
 'Carbon dioxide, from soil or biomass stock' (kilogram, None, ('air', 'low population density, long-term')),
 'Carbon dioxide, to soil or biomass stock' (kilogram, None, ('soil', 'industrial'))]

In [78]:
df

Stream Name Mass Flows  Volume Flow   Type
FEED          120000.0  2379.991137  Input
FEED 2        120000.0  2379.991137  Input
FEED 3        120000.0  2379.991137  Input

In [123]:
in_df = pd.DataFrame(data)
in_df.rename(columns={'index':'Stream Name'}, inplace = True)

In [126]:
act_in = ['c08edadae22b69a76d149da9cde76ca4', None, 'a93562fde1194f64a3c8a71f7015075c']

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

In [125]:
in_df['Activity'] = None

# Assigning values to the rows after the first one
in_df['Activity'] = act_in
in_df

ValueError: Length of values (3) does not match length of index (21)

In [16]:
in_df['Act unit'] = None
for i in range(len(in_df)):
    if in_df.loc[i, 'Activity'] is None:
        in_df.loc[i,'Act unit'] = None
    else:
        in_df.loc[i,'Act unit'] = bd.get_node(code=in_df.loc[i, 'Activity'])['unit']

in_df

,Stream Name,Mass Flows,Volume Flow,Type,Activity,Act unit
0,FEED,120000.0,2379.991137,Input,c08edadae22b69a76d149da9cde76ca4,kilogram
1,FEED 2,120000.0,2379.991137,Input,None,None
2,FEED 3,120000.0,2379.991137,Input,a93562fde1194f64a3c8a71f7015075c,kilogram

In [17]:
out_df = pd.DataFrame(data_out)
out_df.rename(columns={'index':'Stream Name'}, inplace = True)
out_df['Type']=None
out_df['Type']=['Reference flow', 'Waste']
out_df

  Stream Name  Mass Flows  Volume Flow            Type
0        BTMS     73380.0  1334.811905  Reference flow
1        DIST     46620.0  1025.877458           Waste

In [131]:
[[act['name'], act['code']] for act in ei_db.search("electricity natural gas")]

[['electricity production, natural gas, aluminium industry',
  '625600d535dd4094bf61b556059318d7'],
 ['electricity production, natural gas, aluminium industry',
  '6871bfab77376297b0bfc7e7a79db986'],
 ['electricity production, natural gas, aluminium industry',
  '5de2d671cf4b5e44f55106fe26aa67be'],
 ['electricity production, natural gas, conventional power plant',
  'f6af2a9edf780e0c3d8b129e55d4883d'],
 ['electricity production, natural gas, conventional power plant',
  '79443b12ee2bad52369c3d58bf3e703e'],
 ['natural gas, burned in micro gas turbine, 100kWe',
  '6f20c0ffa73418f98750ae36b8132387'],
 ['natural gas, burned in micro gas turbine, 100kWe',
  'ba53d48d9c36a7fa5494684fd1d4a38e'],
 ['electricity production, natural gas, conventional power plant',
  '1655c2192b48df7c50ab836105898ec3'],
 ['electricity production, natural gas, conventional power plant',
  'e303e8c0f0c9d39d5d7a89bfd89a9654'],
 ['electricity production, natural gas, conventional power plant',
  'f8aab43946f0e59bc804d60d268cd76b'],
 ['electricity production, natural gas, conventional power plant',
  '2bf755bada896d15769c93025c9364a0'],
 ['electricity production, natural gas, conventional power plant',
  '6297d49743540f84c38d7a34f8329148'],
 ['electricity production, natural gas, conventional power plant',
  '6f69d0788668933b511a2b6fbaf06948'],
 ['electricity production, natural gas, conventional power plant',
  'd3e7de3c24ea32e7921f6c2d8d5f22ed'],
 ['electricity production, natural gas, conventional power plant',
  '9ea5d4a90d4cb25d71adf9a5c489bbb2'],
 ['electricity production, natural gas, conventional power plant',
  '461bbef1f6d3c45e00d5d3036484c0fa'],
 ['electricity production, natural gas, conventional power plant',
  'e1255855e6be72ffd0767fe7e8b2f416'],
 ['electricity production, natural gas, conventional power plant',
  'adce0f01b7763f2af8f6529a77db2a7a'],
 ['electricity production, natural gas, conventional power plant',
  '1e94be3afae58f6f04d4e2580901e885'],
 ['electricity production, natural gas, conventional power plant',
  'c324c19a2dcd97e369b9f849346a0326'],
 ['electricity production, natural gas, conventional power plant',
  '28550e96adac56301119c76e4ec5e8b8'],
 ['electricity production, natural gas, conventional power plant',
  'f466b3842ff04076f291ec8f8c859342'],
 ['electricity production, natural gas, conventional power plant',
  '3a5f89f4acf125ee2f6d9e7ef6c21713'],
 ['electricity production, natural gas, conventional power plant',
  'ac9e04ced053e9ee425cba23a2864c79'],
 ['electricity production, natural gas, conventional power plant',
  'bd872030cb8cbb0aaf49082f3f5a65b5']]

In [132]:
act_waste = ['f6af2a9edf780e0c3d8b129e55d4883d']

In [133]:
out_df['Activity'] = None

# Assigning values to the rows after the first one
out_df.loc[out_df['Type']=='Waste', 'Activity'] = act_waste
out_df

,Stream Name,Mass Flows,Volume Flow,Type,Activity,Act unit,Amount
0,BTMS,73380.0,1334.811905,Reference flow,None,kilogram,1.000000
1,DIST,46620.0,1025.877458,Waste,f6af2a9edf780e0c3d8b129e55d4883d,kilogram,0.635323

In [136]:
out_df['Act unit'] = None
for i in range(len(out_df)):
    if out_df.loc[i, 'Type']!= "Waste":
        out_df.loc[i,'Act unit'] = "kilogram"
    else:
        out_df.loc[i,'Act unit'] = bd.get_node(code=out_df.loc[i, 'Activity'])['unit']

out_df

,Stream Name,Mass Flows,Volume Flow,Type,Activity,Act unit,Amount
0,BTMS,73380.0,1334.811905,Reference flow,None,kilogram,1.000000
1,DIST,46620.0,1025.877458,Waste,f6af2a9edf780e0c3d8b129e55d4883d,kilowatt hour,0.635323

In [135]:
bd.get_node(code='ac9e04ced053e9ee425cba23a2864c79')['unit']

'kilowatt hour'

In [147]:
def calculate_amount(row, ref_mass_flow):
    if row['Act unit'] == 'kilogram':
        return row['Mass Flows'] / ref_mass_flow
    elif row['Act unit'] == 'cubic metre':
        return row['Volume Flow'] / ref_mass_flow
    elif row['Act unit'] == 'megajoule':
        return row['Duty'] / ref_mass_flow
    elif row['Act unit'] =='kilowatt hour':
        return (row['Mass Flows']/3.6) / ref_mass_flow # to convert MJ in kWh
    else:
        return None

reference_mass_flow=out_df.loc[out_df['Type'] == "Reference flow",'Mass Flows']
# Apply the function to calculate the Amount column
out_df['Amount'] = out_df.apply(calculate_amount, axis=1, ref_mass_flow=reference_mass_flow)
# in_df['Amount'] = in_df.apply(calculate_amount, axis=1, ref_mass_flow=reference_mass_flow)
out_df

,Stream Name,Mass Flows,Volume Flow,Type,Activity,Act unit,Amount
0,BTMS,73380.0,1334.811905,Reference flow,None,kilogram,1.000000
1,DIST,46620.0,1025.877458,Waste,f6af2a9edf780e0c3d8b129e55d4883d,kilowatt hour,0.176479

In [22]:
out_df

,Stream Name,Mass Flows,Volume Flow,Type,Activity,Act unit,Amount
0,BTMS,73380.0,1334.811905,Reference flow,None,kilogram,1.000000
1,DIST,46620.0,1025.877458,Waste,a93562fde1194f64a3c8a71f7015075c,kilogram,0.635323

In [23]:
LCA_setting_df = pd.concat([in_df, out_df])[['Stream Name', 'Type', 'Activity','Act unit','Amount']]

In [24]:
LCA_setting_clean_df=LCA_setting_df.dropna(subset=['Activity']).reset_index(drop=True)
LCA_setting_clean_df

  Stream Name   Type                          Activity  Act unit    Amount
0        FEED  Input  c08edadae22b69a76d149da9cde76ca4  kilogram  1.635323
1      FEED 3  Input  a93562fde1194f64a3c8a71f7015075c  kilogram  1.635323
2        DIST  Waste  a93562fde1194f64a3c8a71f7015075c  kilogram  0.635323

In [25]:
LCIA_df_list=[]
lca_df=LCA_setting_clean_df.copy()

for i in range(len(EF_select)):
    lca_df=LCA_setting_clean_df.copy()
    lca_df['Impact category']=EF_select[i][1]
    lca_df['Impact unit']=str(bd.methods[EF_select[i]]["unit"])
    LCIA_df_list.append(lca_df)

lca_df=pd.concat(LCIA_df_list)
lca_df['Impact'] = 0
lca_df.reset_index(inplace=True, drop=True)

In [28]:
lca_df.loc[lca_df['Impact category']=='climate change', 'Impact unit'].iloc[0]

'kg CO2-Eq'

In [131]:
lca_df

,Stream Name,Type,Activity,Act unit,Amount,Impact category,Impact unit,Impact
0,FEED,Input,c08edadae22b69a76d149da9cde76ca4,kilogram,1.635323,acidification,mol H+-Eq,0
1,FEED 3,Input,a93562fde1194f64a3c8a71f7015075c,kilogram,1.635323,acidification,mol H+-Eq,0
2,DIST,Waste,a93562fde1194f64a3c8a71f7015075c,kilogram,0.635323,acidification,mol H+-Eq,0
3,FEED,Input,c08edadae22b69a76d149da9cde76ca4,kilogram,1.635323,climate change,kg CO2-Eq,0
4,FEED 3,Input,a93562fde1194f64a3c8a71f7015075c,kilogram,1.635323,climate change,kg CO2-Eq,0
...,...,...,...,...,...,...,...,...
70,FEED 3,Input,a93562fde1194f64a3c8a71f7015075c,kilogram,1.635323,photochemical oxidant formation: human health,kg NMVOC-Eq,0
71,DIST,Waste,a93562fde1194f64a3c8a71f7015075c,kilogram,0.635323,photochemical oxidant formation: human health,kg NMVOC-Eq,0
72,FEED,Input,c08edadae22b69a76d149da9cde76ca4,kilogram,1.635323,water use,m3 world Eq deprived,0
73,FEED 3,Input,a93562fde1194f64a3c8a71f7015075c,kilogram,1.635323,water use,m3 world Eq deprived,0
74,DIST,Waste,a93562fde1194f64a3c8a71f7015075c,kilogram,0.635323,water use,m3 world Eq deprived,0

In [132]:
LCA_setting_clean_df['Activity'][0]

'c08edadae22b69a76d149da9cde76ca4'

In [133]:
activity = bd.get_node(code = LCA_setting_clean_df['Activity'][0])

lca = bc.LCA({activity:LCA_setting_clean_df['Amount'][0]}, EF_select[0])
lca.lci()

for j in range(len(LCA_setting_clean_df)):
        activity =bd.get_node(code = LCA_setting_clean_df['Activity'][j])

        lca.redo_lci({activity.id:LCA_setting_clean_df['Amount'][j]})
        for i in range(len(EF_select)):
                lca.switch_method(EF_select[i])
                lca.lcia()
                lca_df.loc[(lca_df['Impact category']==EF_select[i][1]) 
                                &  (lca_df['Activity']==LCA_setting_clean_df['Activity'][j]) ,'Impact']=lca.score
lca_df

C:\Users\niky2\AppData\Local\Temp\ipykernel_15668\952598928.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.001726504337363489' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  lca_df.loc[(lca_df['Impact category']==EF_select[i][1])

,Stream Name,Type,Activity,Act unit,Amount,Impact category,Impact unit,Impact
0,FEED,Input,c08edadae22b69a76d149da9cde76ca4,kilogram,1.635323,acidification,mol H+-Eq,1.726504e-03
1,FEED 3,Input,a93562fde1194f64a3c8a71f7015075c,kilogram,1.635323,acidification,mol H+-Eq,3.163918e-07
2,DIST,Waste,a93562fde1194f64a3c8a71f7015075c,kilogram,0.635323,acidification,mol H+-Eq,3.163918e-07
3,FEED,Input,c08edadae22b69a76d149da9cde76ca4,kilogram,1.635323,climate change,kg CO2-Eq,2.191564e-01
4,FEED 3,Input,a93562fde1194f64a3c8a71f7015075c,kilogram,1.635323,climate change,kg CO2-Eq,4.760799e-05
...,...,...,...,...,...,...,...,...
70,FEED 3,Input,a93562fde1194f64a3c8a71f7015075c,kilogram,1.635323,photochemical oxidant formation: human health,kg NMVOC-Eq,2.075772e-07
71,DIST,Waste,a93562fde1194f64a3c8a71f7015075c,kilogram,0.635323,photochemical oxidant formation: human health,kg NMVOC-Eq,2.075772e-07
72,FEED,Input,c08edadae22b69a76d149da9cde76ca4,kilogram,1.635323,water use,m3 world Eq deprived,1.693342e-01
73,FEED 3,Input,a93562fde1194f64a3c8a71f7015075c,kilogram,1.635323,water use,m3 world Eq deprived,1.549138e-04
74,DIST,Waste,a93562fde1194f64a3c8a71f7015075c,kilogram,0.635323,water use,m3 world Eq deprived,1.549138e-04